/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 

/**
 *
 * @author Konrad Sautter
 */
public class impfenGUI extends javax.swing.JFrame {

    /**
     * Creates new form impfenGUI
     */
    public impfenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        pImpfen = new javax.swing.JPanel();
        pKleinImpfen = new javax.swing.JPanel();
        tfImpfenImpfung = new javax.swing.JTextField();
        tfImpfenName = new javax.swing.JTextField();
        btImpfenImpfen = new javax.swing.JButton();
        spImpfen = new javax.swing.JScrollPane();
        taImpfenOUT = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        pPatient = new javax.swing.JPanel();
        pSuchen = new javax.swing.JPanel();
        tfSuchenName = new javax.swing.JTextField();
        btSuchen = new javax.swing.JButton();
        lbSuchen = new javax.swing.JLabel();
        spSuchen = new javax.swing.JScrollPane();
        taSuchenOUT = new javax.swing.JTextArea();
        pHinzufuegen = new javax.swing.JPanel();
        tfHzfName = new javax.swing.JTextField();
        tfHzfGeb = new javax.swing.JTextField();
        tfHzfGeschl = new javax.swing.JTextField();
        tfHzfAdr = new javax.swing.JTextField();
        tfHzfNum = new javax.swing.JTextField();
        btHzf = new javax.swing.JButton();
        lbHinzufuegen = new javax.swing.JLabel();
        spHzfg = new javax.swing.JScrollPane();
        taHzfgOUT = new javax.swing.JTextArea();
        pDatenAendern = new javax.swing.JPanel();
        tfDatenZuAendern = new javax.swing.JTextField();
        tfDatenPatientName = new javax.swing.JTextField();
        tfDatenNeu = new javax.swing.JTextField();
        btDatenAendern = new javax.swing.JButton();
        lbDaten = new javax.swing.JLabel();
        spDaten = new javax.swing.JScrollPane();
        taDatenOUT = new javax.swing.JTextArea();
        sbPatient = new javax.swing.JScrollBar();
        pLoeschen1 = new javax.swing.JPanel();
        tfLoeschenName = new javax.swing.JTextField();
        btLoeschen = new javax.swing.JButton();
        lbLoeschen = new javax.swing.JLabel();
        spLoeschen = new javax.swing.JScrollPane();
        taLoeschenOUT = new javax.swing.JTextArea();
        pInformation = new javax.swing.JPanel();
        pStatus = new javax.swing.JPanel();
        tfStatusName = new javax.swing.JTextField();
        tfStatusImpfung = new javax.swing.JTextField();
        btStatusAbfragen = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        spStatus = new javax.swing.JScrollPane();
        taStatusOUT = new javax.swing.JTextArea();
        pAllgStat = new javax.swing.JPanel();
        tfAllgStatName = new javax.swing.JTextField();
        btAllgStat = new javax.swing.JButton();
        lbAllgStat = new javax.swing.JLabel();
        spAllgStat = new javax.swing.JScrollPane();
        taAllgStatOUT = new javax.swing.JTextArea();
        pInfo = new javax.swing.JPanel();
        tfInfoName = new javax.swing.JTextField();
        tfInfoImpfung = new javax.swing.JTextField();
        btInfo = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();
        spInfo = new javax.swing.JScrollPane();
        taInfoOUT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        tfImpfenImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfImpfenImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfImpfenImpfung.setText("Impfung");
        tfImpfenImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfImpfenImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImpfenImpfungActionPerformed(evt);
            }
        });

        tfImpfenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfImpfenName.setForeground(new java.awt.Color(102, 102, 102));
        tfImpfenName.setText("Name eingeben");
        tfImpfenName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfImpfenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImpfenNameActionPerformed(evt);
            }
        });

        btImpfenImpfen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImpfenImpfen.setText("Impfen");
        btImpfenImpfen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImpfenImpfenActionPerformed(evt);
            }
        });

        taImpfenOUT.setColumns(20);
        taImpfenOUT.setRows(5);
        spImpfen.setViewportView(taImpfenOUT);

        javax.swing.GroupLayout pKleinImpfenLayout = new javax.swing.GroupLayout(pKleinImpfen);
        pKleinImpfen.setLayout(pKleinImpfenLayout);
        pKleinImpfenLayout.setHorizontalGroup(
            pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKleinImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spImpfen)
                    .addGroup(pKleinImpfenLayout.createSequentialGroup()
                        .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfImpfenName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfImpfenImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(btImpfenImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(397, 397, 397))
        );

        pKleinImpfenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfImpfenImpfung, tfImpfenName});

        pKleinImpfenLayout.setVerticalGroup(
            pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKleinImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btImpfenImpfen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pKleinImpfenLayout.createSequentialGroup()
                        .addComponent(tfImpfenName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(tfImpfenImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pKleinImpfenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfImpfenImpfung, tfImpfenName});

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Impfen");

        javax.swing.GroupLayout pImpfenLayout = new javax.swing.GroupLayout(pImpfen);
        pImpfen.setLayout(pImpfenLayout);
        pImpfenLayout.setHorizontalGroup(
            pImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pKleinImpfen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pImpfenLayout.setVerticalGroup(
            pImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pKleinImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Impfen", pImpfen);

        tfSuchenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSuchenName.setForeground(new java.awt.Color(102, 102, 102));
        tfSuchenName.setText("Name eingeben\n");
        tfSuchenName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfSuchenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSuchenNameActionPerformed(evt);
            }
        });

        btSuchen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSuchen.setText("Suchen");
        btSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuchenActionPerformed(evt);
            }
        });

        lbSuchen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSuchen.setText("Suchen");

        taSuchenOUT.setColumns(20);
        taSuchenOUT.setRows(5);
        spSuchen.setViewportView(taSuchenOUT);

        javax.swing.GroupLayout pSuchenLayout = new javax.swing.GroupLayout(pSuchen);
        pSuchen.setLayout(pSuchenLayout);
        pSuchenLayout.setHorizontalGroup(
            pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSuchenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spSuchen)
                    .addGroup(pSuchenLayout.createSequentialGroup()
                        .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(tfSuchenName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addComponent(btSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSuchenLayout.setVerticalGroup(
            pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSuchenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfSuchenName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tfHzfName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfName.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfName.setText("Name eingeben");
        tfHzfName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfHzfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfNameActionPerformed(evt);
            }
        });

        tfHzfGeb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfGeb.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfGeb.setText("Geburtstag");
        tfHzfGeb.setPreferredSize(new java.awt.Dimension(100, 23));
        tfHzfGeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfGebActionPerformed(evt);
            }
        });

        tfHzfGeschl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfGeschl.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfGeschl.setText("Geschlecht");
        tfHzfGeschl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfGeschlActionPerformed(evt);
            }
        });

        tfHzfAdr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfAdr.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfAdr.setText("Adresse");
        tfHzfAdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfAdrActionPerformed(evt);
            }
        });

        tfHzfNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfNum.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfNum.setText("Telefonnummer");
        tfHzfNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfNumActionPerformed(evt);
            }
        });

        btHzf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btHzf.setText("Hinzufügen");
        btHzf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHzfActionPerformed(evt);
            }
        });

        lbHinzufuegen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbHinzufuegen.setText("Hinzufügen");

        taHzfgOUT.setColumns(20);
        taHzfgOUT.setRows(5);
        spHzfg.setViewportView(taHzfgOUT);

        javax.swing.GroupLayout pHinzufuegenLayout = new javax.swing.GroupLayout(pHinzufuegen);
        pHinzufuegen.setLayout(pHinzufuegenLayout);
        pHinzufuegenLayout.setHorizontalGroup(
            pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHinzufuegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHzfName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(tfHzfGeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfHzfGeschl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfHzfAdr)
                    .addComponent(tfHzfNum, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btHzf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spHzfg, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pHinzufuegenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfHzfAdr, tfHzfGeb, tfHzfGeschl, tfHzfName, tfHzfNum});

        pHinzufuegenLayout.setVerticalGroup(
            pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHinzufuegenLayout.createSequentialGroup()
                .addComponent(lbHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfHzfName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pHinzufuegenLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tfHzfAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pHinzufuegenLayout.createSequentialGroup()
                        .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHzfNum, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(tfHzfGeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pHinzufuegenLayout.createSequentialGroup()
                                .addComponent(tfHzfGeschl)
                                .addGap(5, 5, 5))
                            .addComponent(btHzf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(spHzfg)))
        );

        pHinzufuegenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfHzfAdr, tfHzfGeb, tfHzfGeschl, tfHzfName, tfHzfNum});

        tfDatenZuAendern.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenZuAendern.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenZuAendern.setText("zu Ändernde Daten");
        tfDatenZuAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatenZuAendernActionPerformed(evt);
            }
        });

        tfDatenPatientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenPatientName.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenPatientName.setText("Name Patient");
        tfDatenPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatenPatientNameActionPerformed(evt);
            }
        });

        tfDatenNeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenNeu.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenNeu.setText("Neue Daten");
        tfDatenNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatenNeuActionPerformed(evt);
            }
        });

        btDatenAendern.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDatenAendern.setText("Daten Ändern");
        btDatenAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDatenAendernActionPerformed(evt);
            }
        });

        lbDaten.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDaten.setText("Daten Ändern");

        taDatenOUT.setColumns(20);
        taDatenOUT.setRows(5);
        spDaten.setViewportView(taDatenOUT);

        javax.swing.GroupLayout pDatenAendernLayout = new javax.swing.GroupLayout(pDatenAendern);
        pDatenAendern.setLayout(pDatenAendernLayout);
        pDatenAendernLayout.setHorizontalGroup(
            pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatenAendernLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbDaten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDatenZuAendern, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(tfDatenNeu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDatenPatientName, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(41, 41, 41)
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spDaten, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pDatenAendernLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDatenNeu, tfDatenZuAendern});

        pDatenAendernLayout.setVerticalGroup(
            pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatenAendernLayout.createSequentialGroup()
                .addComponent(lbDaten, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatenAendernLayout.createSequentialGroup()
                        .addComponent(btDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spDaten))
                    .addGroup(pDatenAendernLayout.createSequentialGroup()
                        .addComponent(tfDatenPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDatenZuAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDatenNeu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        pDatenAendernLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDatenNeu, tfDatenPatientName, tfDatenZuAendern});

        tfLoeschenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfLoeschenName.setForeground(new java.awt.Color(102, 102, 102));
        tfLoeschenName.setText("Name eingeben\n");
        tfLoeschenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoeschenNameActionPerformed(evt);
            }
        });

        btLoeschen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLoeschen.setText("Löschen");
        btLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoeschenActionPerformed(evt);
            }
        });

        lbLoeschen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLoeschen.setText("Löschen");

        taLoeschenOUT.setColumns(20);
        taLoeschenOUT.setRows(5);
        spLoeschen.setViewportView(taLoeschenOUT);

        javax.swing.GroupLayout pLoeschen1Layout = new javax.swing.GroupLayout(pLoeschen1);
        pLoeschen1.setLayout(pLoeschen1Layout);
        pLoeschen1Layout.setHorizontalGroup(
            pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoeschen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spLoeschen)
                    .addGroup(pLoeschen1Layout.createSequentialGroup()
                        .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbLoeschen, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(tfLoeschenName))
                        .addGap(63, 63, 63)
                        .addComponent(btLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLoeschen1Layout.setVerticalGroup(
            pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoeschen1Layout.createSequentialGroup()
                .addComponent(lbLoeschen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfLoeschenName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pPatientLayout = new javax.swing.GroupLayout(pPatient);
        pPatient.setLayout(pPatientLayout);
        pPatientLayout.setHorizontalGroup(
            pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pLoeschen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDatenAendern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pPatientLayout.setVerticalGroup(
            pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pHinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pLoeschen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(sbPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Patient", pPatient);

        tfStatusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfStatusName.setForeground(new java.awt.Color(102, 102, 102));
        tfStatusName.setText("Name eingeben");
        tfStatusName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfStatusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusNameActionPerformed(evt);
            }
        });

        tfStatusImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfStatusImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfStatusImpfung.setText("Impfung");
        tfStatusImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfStatusImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusImpfungActionPerformed(evt);
            }
        });

        btStatusAbfragen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btStatusAbfragen.setText("Abfragen");
        btStatusAbfragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStatusAbfragenActionPerformed(evt);
            }
        });

        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbStatus.setText("Status");

        taStatusOUT.setColumns(20);
        taStatusOUT.setRows(5);
        spStatus.setViewportView(taStatusOUT);

        javax.swing.GroupLayout pStatusLayout = new javax.swing.GroupLayout(pStatus);
        pStatus.setLayout(pStatusLayout);
        pStatusLayout.setHorizontalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spStatus)
                    .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pStatusLayout.createSequentialGroup()
                            .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfStatusName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfStatusImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(51, 51, 51)
                            .addComponent(btStatusAbfragen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pStatusLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfStatusImpfung, tfStatusName});

        pStatusLayout.setVerticalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btStatusAbfragen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pStatusLayout.createSequentialGroup()
                        .addComponent(tfStatusName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfStatusImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pStatusLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfStatusImpfung, tfStatusName});

        tfAllgStatName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAllgStatName.setForeground(new java.awt.Color(102, 102, 102));
        tfAllgStatName.setText("Name eingeben");
        tfAllgStatName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfAllgStatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAllgStatNameActionPerformed(evt);
            }
        });

        btAllgStat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllgStat.setText("Abfragen");
        btAllgStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllgStatActionPerformed(evt);
            }
        });

        lbAllgStat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAllgStat.setText("Allgemeiner Status");

        taAllgStatOUT.setColumns(20);
        taAllgStatOUT.setRows(5);
        spAllgStat.setViewportView(taAllgStatOUT);

        javax.swing.GroupLayout pAllgStatLayout = new javax.swing.GroupLayout(pAllgStat);
        pAllgStat.setLayout(pAllgStatLayout);
        pAllgStatLayout.setHorizontalGroup(
            pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAllgStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAllgStat)
                    .addGroup(pAllgStatLayout.createSequentialGroup()
                        .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btAllgStat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAllgStatName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(spAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAllgStatLayout.setVerticalGroup(
            pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAllgStatLayout.createSequentialGroup()
                .addComponent(lbAllgStat, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAllgStatLayout.createSequentialGroup()
                        .addComponent(tfAllgStatName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spAllgStat))
                .addContainerGap())
        );

        tfInfoName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfInfoName.setForeground(new java.awt.Color(102, 102, 102));
        tfInfoName.setText("Name eingeben");
        tfInfoName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfInfoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInfoNameActionPerformed(evt);
            }
        });

        tfInfoImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfInfoImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfInfoImpfung.setText("Impfung");
        tfInfoImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfInfoImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInfoImpfungActionPerformed(evt);
            }
        });

        btInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInfo.setText("Suchen");
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });

        lbInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbInfo.setText("Information");

        taInfoOUT.setColumns(20);
        taInfoOUT.setRows(5);
        spInfo.setViewportView(taInfoOUT);

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfInfoImpfung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(spInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfInfoName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfInfoImpfung, tfInfoName});

        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfInfoName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(tfInfoImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spInfo))
                .addContainerGap())
        );

        pInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfInfoImpfung, tfInfoName});

        javax.swing.GroupLayout pInformationLayout = new javax.swing.GroupLayout(pInformation);
        pInformation.setLayout(pInformationLayout);
        pInformationLayout.setHorizontalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAllgStat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pInformationLayout.setVerticalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Information", pInformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfStatusImpfungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStatusImpfungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStatusImpfungActionPerformed

    private void tfInfoImpfungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInfoImpfungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInfoImpfungActionPerformed

    private void tfImpfenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImpfenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfImpfenNameActionPerformed

    private void tfImpfenImpfungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImpfenImpfungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfImpfenImpfungActionPerformed

    private void tfSuchenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSuchenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSuchenNameActionPerformed

    private void tfHzfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHzfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHzfNameActionPerformed

    private void btImpfenImpfenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImpfenImpfenActionPerformed
        // TODO add your handling code here:
        taImpfenOUT.setText("Der Patient wurde geimpft");
            
    }//GEN-LAST:event_btImpfenImpfenActionPerformed

    private void btDatenAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDatenAendernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDatenAendernActionPerformed

    private void btStatusAbfragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStatusAbfragenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStatusAbfragenActionPerformed

    private void tfStatusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStatusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStatusNameActionPerformed

    private void tfAllgStatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAllgStatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAllgStatNameActionPerformed

    private void btAllgStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllgStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAllgStatActionPerformed

    private void tfInfoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInfoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInfoNameActionPerformed

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInfoActionPerformed

    private void btSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuchenActionPerformed

    private void tfHzfGebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHzfGebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHzfGebActionPerformed

    private void tfHzfGeschlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHzfGeschlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHzfGeschlActionPerformed

    private void tfHzfAdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHzfAdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHzfAdrActionPerformed

    private void tfHzfNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHzfNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHzfNumActionPerformed

    private void btHzfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHzfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHzfActionPerformed

    private void tfLoeschenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoeschenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoeschenNameActionPerformed

    private void btLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoeschenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoeschenActionPerformed

    private void tfDatenPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatenPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatenPatientNameActionPerformed

    private void tfDatenZuAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatenZuAendernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatenZuAendernActionPerformed

    private void tfDatenNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatenNeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatenNeuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impfenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btAllgStat;
    private javax.swing.JButton btDatenAendern;
    private javax.swing.JButton btHzf;
    private javax.swing.JButton btImpfenImpfen;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JButton btStatusAbfragen;
    private javax.swing.JButton btSuchen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAllgStat;
    private javax.swing.JLabel lbDaten;
    private javax.swing.JLabel lbHinzufuegen;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLoeschen;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbSuchen;
    private javax.swing.JPanel pAllgStat;
    private javax.swing.JPanel pDatenAendern;
    private javax.swing.JPanel pHinzufuegen;
    private javax.swing.JPanel pImpfen;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPanel pInformation;
    private javax.swing.JPanel pKleinImpfen;
    private javax.swing.JPanel pLoeschen1;
    private javax.swing.JPanel pPatient;
    private javax.swing.JPanel pStatus;
    private javax.swing.JPanel pSuchen;
    private javax.swing.JScrollBar sbPatient;
    private javax.swing.JScrollPane spAllgStat;
    private javax.swing.JScrollPane spDaten;
    private javax.swing.JScrollPane spHzfg;
    private javax.swing.JScrollPane spImpfen;
    private javax.swing.JScrollPane spInfo;
    private javax.swing.JScrollPane spLoeschen;
    private javax.swing.JScrollPane spStatus;
    private javax.swing.JScrollPane spSuchen;
    private javax.swing.JTextArea taAllgStatOUT;
    private javax.swing.JTextArea taDatenOUT;
    private javax.swing.JTextArea taHzfgOUT;
    private javax.swing.JTextArea taImpfenOUT;
    private javax.swing.JTextArea taInfoOUT;
    private javax.swing.JTextArea taLoeschenOUT;
    private javax.swing.JTextArea taStatusOUT;
    private javax.swing.JTextArea taSuchenOUT;
    private javax.swing.JTextField tfAllgStatName;
    private javax.swing.JTextField tfDatenNeu;
    private javax.swing.JTextField tfDatenPatientName;
    private javax.swing.JTextField tfDatenZuAendern;
    private javax.swing.JTextField tfHzfAdr;
    private javax.swing.JTextField tfHzfGeb;
    private javax.swing.JTextField tfHzfGeschl;
    private javax.swing.JTextField tfHzfName;
    private javax.swing.JTextField tfHzfNum;
    private javax.swing.JTextField tfImpfenImpfung;
    private javax.swing.JTextField tfImpfenName;
    private javax.swing.JTextField tfInfoImpfung;
    private javax.swing.JTextField tfInfoName;
    private javax.swing.JTextField tfLoeschenName;
    private javax.swing.JTextField tfStatusImpfung;
    private javax.swing.JTextField tfStatusName;
    private javax.swing.JTextField tfSuchenName;
    // End of variables declaration//GEN-END:variables
}
